Repository CSC207-2022F-UofT/course-project-my-dog-ate-my-hw, pull requests merged in 2022-12, with the labels that each got.

#67 [Feature 20] User UC and Output Boundaries
  src/main/java/useCases/MainOutputBoundary.java
  src/main/java/useCases/PetUIDS.java
  src/main/java/useCases/Refresher.java
  src/main/java/useCases/RefresherFactory.java
  src/main/java/useCases/TaskUIDS.java
  src/main/java/useCases/TasklistOutputBoundary.java
  src/main/java/useCases/User.java
Labels: enhancement

#64 [Feature 17] CompleteTaskUC and BuyItemUC
  src/main/java/entities/AbsentItemNameException.java
  src/main/java/entities/Customization.java
  src/main/java/entities/Pet.java
  src/main/java/entities/Priority.java
  src/main/java/entities/User.java
  src/main/java/uiControllers/CompleteTaskControl.java
  src/main/java/useCases/BuyHatUC.java
  src/main/java/useCases/BuyItemInputBoundary.java
  src/main/java/useCases/BuyItemUC.java
  src/main/java/useCases/CompleteTaskInputBoundary.java
  src/main/java/useCases/CompleteTaskUC.java
  src/main/java/useCases/GainPointsUC.java
  src/main/java/useCases/RouletteInputBoundary.java
  src/main/java/useCases/RouletteUC.java
  src/main/java/useCases/User.java
  src/main/java/useCases/UserUC.java
  src/test/java/entities/UserTest.java
  src/test/java/useCases/BuyHatUCTest.java
  src/test/java/useCases/BuyItemUCTest.java
  src/test/java/useCases/CompleteTaskUCTest.java
Labels: documentation, enhancement

#77 [Feature 24] Entity Tests and Use Case Updates
  src/main/java/controllers/BuyHeartController.java
  src/main/java/entities/Item.java
  src/main/java/entities/Pet.java
  src/main/java/entities/ToDoList.java
  src/main/java/uiControllers/PetShopUIController.java
  src/main/java/useCases/AdoptPetInputBoundary.java
  src/main/java/useCases/AdoptPetUC.java
  src/main/java/useCases/BuyHeartUC.java
  src/main/java/useCases/BuyItemUC.java
  src/main/java/useCases/PetOutputBoundary.java
  src/main/java/useCases/PetRefresher.java
  src/main/java/useCases/TasklistRefresher.java
  src/main/java/useCases/UserUC.java
  src/test/java/entities/CustomizationTest.java
  src/test/java/entities/DoneListTest.java
  src/test/java/entities/HatTest.java
  src/test/java/entities/ItemTest.java
  src/test/java/entities/PetTest.java
  src/test/java/entities/ToDoListTest.java
  src/test/java/entities/UserTest.java
  src/test/java/useCases/BuyItemUCTest.java
  src/test/java/useCases/ToDoListTest.java
Labels: enhancement

#78 [Feature 23] Load and Save Data
  src/main/java/Main.java
  src/main/java/database/CustomizationDB.java
  src/main/java/database/DataLogger.java
  src/main/java/database/DataSaver.java
  src/main/java/database/ItemDB.java
  src/main/java/database/PetDB.java
  src/main/java/database/TaskDB.java
  src/main/java/database/UserDB.java
  src/main/java/databaseBoundaries/CustomizationDBBoundary.java
  src/main/java/databaseBoundaries/DataLoggerBoundary.java
  src/main/java/databaseBoundaries/ItemDBBoundary.java
  src/main/java/databaseBoundaries/PetDBBoundary.java
  src/main/java/databaseBoundaries/TaskDBBoundary.java
  src/main/java/databaseBoundaries/UserDBBoundary.java
  src/main/java/entities/Checklist.java
  src/main/java/entities/Customization.java
  src/main/java/entities/Task.java
  src/main/java/ui/ViewRefresher.java
  src/main/java/useCases/BuyHeartUC.java
  src/main/java/useCases/LoadUserUC.java
  src/main/java/useCases/ModifyTaskUC.java
  src/main/java/useCases/PetRefresher.java
  src/main/java/useCases/SaveUserUC.java
  src/main/java/useCases/TasklistRefresher.java
  src/test/java/entities/DoneListTest.java
  src/test/java/entities/TaskTest.java
  src/test/java/entities/ToDoListTest.java
  src/test/java/useCases/CheckerUCTest.java
  src/test/java/useCases/CompleteTaskUCTest.java
  src/test/java/useCases/CreateTaskUCTest.java
  src/test/java/useCases/RouletteUCTest.java
Labels: enhancement

#87 [Debugging 1] Pet Harm and Healing
  src/main/java/entities/Customization.java
  src/main/java/entities/Pet.java
  src/main/java/ui/ViewRefresher.java
  src/main/java/useCases/BuyHeartUC.java
  src/main/java/useCases/CheckerUC.java
  src/main/java/useCases/LoadUserUC.java
Labels: bug
